apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: multi-container-app-todo-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        - containerPort: 35729
        env:
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  selector:
    app: todo-app
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: live-reload
      protocol: TCP
      port: 35729
      targetPort: 35729
  type: NodePort
